const SerCardsArr = [
  {
    id: 1,
    imgsrc: "https://i.ibb.co/7Qqz35g/ser1logo.webp",
    imghover: "https://i.ibb.co/L05TMLk/ser1logohover.webp",
    title: "Customized Solution Development",
    para: "Our dedicated team of experts software developer gives you the best custom software development services worldwide.",
  },
  {
    id: 2,
    imgsrc: "https://i.ibb.co/72gM93G/cardspics-12.webp",
    imghover: "https://i.ibb.co/NtnhdFp/cardspics-11.webp",
    title: "Digital Transformation",
    para: "Techxcape digitally transforms the organization's through ir's Digital Marketing and IT Solution services and by doing this we lead organizations towards a continuous improvement stage.",
  },
  {
    id: 3,
    imgsrc: "https://i.ibb.co/Y7sDH9P/cardspics-2.webp",
    imghover: "https://i.ibb.co/N3sqXPM/cardspics-1.webp",
    title: "Technical Human resourcing",
    para: "When it comes to website development, we push the limits and set new standards by creating functionally rich and aesthetically stunning websites.",
  },
  {
    id: 4,
    imgsrc: "https://i.ibb.co/vZD3YV6/cardspics-10.webp",
    imghover: "https://i.ibb.co/gjQM5g1/cardspics-9.webp",
    title: "Oracle Implementation",
    para: "Techxcape empowers organizations with its Oracle Implementation Services and unlocks their true potential by leveraging organizations planning and accounting processes with intuitive cloud based tools.",
  },
  {
    id: 5,
    imgsrc: "https://i.ibb.co/0KndCMY/cardspics-16.webp",
    imghover: "https://i.ibb.co/LvsqhmX/cardspics-15.webp",
    title: "Web Development",
    para: "When it comes to website development, we push the limits and set new standards by creating functionally rich and aesthetically stunning websites.",
  },
  {
    id: 6,
    imgsrc: "https://i.ibb.co/3zwxskh/cardspics-8.webp",
    imghover: "https://i.ibb.co/DptLW89/cardspics-7.webp",
    title: "Mobile Apps Development",
    para: "We are a leading mobile app development company for enterprise level entities, We can build robust, fully scalable and secure mobile apps.",
  },
  {
    id: 7,
    imgsrc: "https://i.ibb.co/2jmWzsc/cardspics-6.webp",
    imghover: "https://i.ibb.co/NtK4n5J/cardspics-5.webp",
    title: "Ecommerce Development",
    para: "A compelling e-commerce design requires creativity, innovation, skill and experience on part of the developer",
  },
  {
    id: 8,
    imgsrc: "https://i.ibb.co/w43zh8J/cardspics-14.webp",
    imghover: "https://i.ibb.co/DptLW89/cardspics-7.webp",
    title: "Creative UI/UX designing",
    para: "We specialize in UI/UX Design, being a specialist we have a design-centric approach to user interface and user experience design.",
  },
  {
    id: 9,
    imgsrc: "https://i.ibb.co/tH9gsbF/cardspics-4.webp",
    imghover: "https://i.ibb.co/LYsHKCZ/cardspics-3.webp",
    title: "Digital Marketing",
    para: "Our marketing strategy is centered around helping you grow your business and reach out to millions of people.",
  },
  {
    id: 10,
    imgsrc: "https://i.ibb.co/tH9gsbF/cardspics-4.webp",
    imghover: "https://i.ibb.co/LYsHKCZ/cardspics-3.webp",
    title: "Data Science",
    para: "At TechXcape, We pride ourselves on being an early adopter of artificial intelligence & blockchain. We connect data, science & innovative digital research solutions to provide answers for key business questions around consumers, markets, brands & media. We Dive Deep across all our customer & business KPIs.",
  },
  {
    id: 11,
    imgsrc: "https://i.ibb.co/tH9gsbF/cardspics-4.webp",
    imghover: "https://i.ibb.co/LYsHKCZ/cardspics-3.webp",
    title: "Block chain",
    para: "We at Techxcape has delivered many blockchain Techniques in industries like payments, cybersecurity & healthcare to provide them transaction’s recording & Security, We believe in detail & thus, use our data to optimize our processes, drive action & deliver results.",
  },
  {
    id: 12,
    imgsrc: "https://i.ibb.co/tH9gsbF/cardspics-4.webp",
    imghover: "https://i.ibb.co/LYsHKCZ/cardspics-3.webp",
    title: "Internet Of Things",
    para: "We provide fully functional systems which embedded with sensors, software, and other technologies for the purpose of connecting and exchanging data with other devices and systems over the internet.",
  },
  {
    id: 13,
    imgsrc: "https://i.ibb.co/tH9gsbF/cardspics-4.webp",
    imghover: "https://i.ibb.co/LYsHKCZ/cardspics-3.webp",
    title: "Artificial Intelligence",
    para: "TechXcape provide artificial intelligence systems, powered by AI, ML and deep learning, which makes those systems to performs tasks that ordinarily require human intelligence, From which our clients has improved their performance drastically.",
  },
];

export default SerCardsArr;
